server {
    listen 80;
    
    root /usr/share/nginx/html;
    index index.html;

    location /client/ {
        try_files $uri $uri/ /client/index.html;
    }

    location /api/ {
        proxy_pass http://server:5000;
    }

    location /dashboard/ {
        proxy_pass http://server:5000;
    }
}
